### ISSUE TITLE
External dependency is not added to node_modules

### ISSUE THREAD

**Issue by ipauler** [floydspace/serverless-esbuild#103] opened 2021-03-24 22:12 UTC
I have an external dependency 'A' which is needed by other external dependency 'B'.
'A' is not used in my code so when function got bundled it doesn't adds 'A' into node_modules.
Is there a workaround for that ? Or maybe i can create a PR with a fix for that ?

**Comment by olup** [comment] 2021-03-24 22:17
If A is declared as external, it should be added to your node modules with all it's dependencies. If you only declare b as external it's indeed more complicated. What is your situation ? What did you declare in your external config ? And, for the record, what packages are your A and B ?

**Comment by ipauler** [comment] 2021-03-24 22:23
yes i'm doing individual packaging 
so the issue is with `util-deprecate` 
```
  "Runtime.ImportModuleError: Error: Cannot find module 'util-deprecate'",
        "Require stack:",
        "- /var/task/node_modules/readable-stream/lib/_stream_writable.js",
        "- /var/task/node_modules/readable-stream/readable.js",
        "- /var/task/node_modules/split2/index.js",
        "- /var/task/node_modules/pgpass/lib/helper.js",
        "- /var/task/node_modules/pgpass/lib/index.js",
        "- /var/task/node_modules/pg/lib/client.js",
        "- /var/task/node_modules/pg/lib/index.js",
        "- /var/task/src/app/graphql/handler.js",
 ```
`pg` is external in my case because it's not working other way

**Comment by olup** [comment] 2021-03-24 22:48
Last question, are you in a mononrepo / workspace ? Are you bundling on you computer or in the cloud ? And in the former case, what os are you on ? Can you confirm util-deprecate is found in your local node_modules ?

**Comment by ipauler** [comment] 2021-03-24 22:55
yarn workspaces
util-deprecate is in node_modules in root dir 
trying building it locally on mac and in CodeBuild with linux same result

**Comment by olup** [comment] 2021-03-24 23:04
Thank you, I'll try to reproduce the error in the morning here.

**Comment by olup** [comment] 2021-03-25 08:10
Would you mind sharing either a repo, either a copy-paste copy of your `package.json` (in your workspace and in the root) and your `serverless.yml`, so that I can reproduce a similar setup ?

**Comment by gusfune** [comment] 2021-04-16 17:16
Hi, we are using a monorepo and the same issue is happening with us. In one function that we use `import Shopify from "shopify-api-node"` we get an error:

```
Error: Cannot find module './carrier-service'
Require stack:
- /orders/.esbuild/.build/src/orders/add_product.js
- /orders/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js
- /orders/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/index.js
- /orders/node_modules/serverless-offline/dist/lambda/handler-runner/child-process-runner/childProcessHelper.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at ve.get (/orders/.esbuild/.build/src/orders/add_product.js:27:34332)
    at update_shipping_methods (/orders/.esbuild/.build/src/orders/add_product.js:267:2177)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async Object.index (/orders/.esbuild/.build/src/orders/add_product.js:406:2242) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/orders/.esbuild/.build/src/orders/add_product.js',
    '/orders/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/InProcessRunner.js',
    '/orders/node_modules/serverless-offline/dist/lambda/handler-runner/in-process-runner/index.js',
    '/orders/node_modules/serverless-offline/dist/lambda/handler-runner/child-process-runner/childProcessHelper.js'
  ]
```

My `serverless.yml` for this project has this config that might be relevant:
```
esbuild:
    bundle: true
    keepNames: true
    minify: true
    packager: yarn
    sourcemap: true
    target: es2018
    loader:
      .graphql: text
      .gql: text
    watch:
      ignore: [".serverless/**/*", ".build", "node_modules"]

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - .gitattributes
    - .prettierrc
    - package.json
    - codegen.yml
    - tsconfig.json
    - README.md
    - yarn.lock
    - node_modules/**
    - .env.*
    - .build/**

plugins:
  - serverless-plugin-datadog
  - serverless-esbuild
  - serverless-domain-manager
  - serverless-offline
  - serverless-prune-plugin
```

In the root level the `package.json` is:
```
{
  "name": "my-services",
  "version": "1.0.0",
  "private": true,
  "devDependencies": {
    "husky": "^6.0.0",
    "lerna": "^4.0.0"
  },
  "scripts": {
    "prepare": "husky install"
  }
}
```

and on `lerna.json`:
```
{
  "packages": [
    "one/*",
    "two/*",
    "three/*",
    "orders/*",
    "five/*",
    "six/*"
  ],
  "npmClient": "yarn",
  "version": "0.0.0"
}
```

I am not using Yarn Workspaces as this was already proven to not help with the dependencies. I am trying to move this project from webpack to esbuild.
Weirdly, another service, the one with a small set of dependencies, is working. Just two of them get this error, which are the more complex ones.

**Comment by olup** [comment] 2021-04-16 19:44
HEy ! Thanks for reporting ! I'd be happy to help you out on this one and unearth bug on our end. However this doe not seem an easy setup to reproduce. Would you be open to share you repo ? Or a test one that shows the problem ?

Cheers !

**Comment by gusfune** [comment] 2021-04-17 10:17
Hi @olup this can be tricky because of our services being tightly attached to Hasura. But hopefully, you'll be able to find something with the downsized version. Here: https://github.com/gusfune/downsize
Let me know if you want me to run any specific tests locally.

**Comment by olup** [comment] 2021-04-17 19:15
@gusfune a bit of context - if I understand correctly you have this error when trying to run your project in a local "serverless-offline" environment ?

**Comment by gusfune** [comment] 2021-04-18 09:59
Correct @olup it happens on serverless-offline, when I try to call the request I put as example on the README.md

**Comment by philiiiiiipp** [comment] 2021-06-07 09:54
Wondering if this is related, but I have uncovered some odd behaviour when bundling external dependencies

I am wondering if 
https://github.com/floydspace/serverless-esbuild/blob/master/src/pack-externals.ts#L78

should not actually be
```ts
  const packageJson = require(rootPackageJsonPath);
```

It seems odd to me, that it would use the package.json of `serverless-esbuild` here instead of the projects `package.json`. In our case this resulted in dev dependencies being bundled as if they where prod dependencies because 

```ts
if (!packageJson.devDependencies || !packageJson.devDependencies[externalModule.external]) {
        prodModules.push(externalModule.external);
      } else {
```

referred to the package.json of serverless-esbuild and therefore would always add them. I am still in the process of validating this but it might be related.

**Comment by danionescu** [comment] 2022-01-06 11:28
Hello, everyone, the reason why this happens is because the dependencies graph generated by npm does not include all the dependencies for all the packages, some of them being duplicates. The issue happens here https://github.com/floydspace/serverless-esbuild/blob/master/src/helper.ts#L81. For example, if I run `` in my project,

mongoose will have:
```
    "mongoose": {
      "version": "6.1.5",
      "resolved": "https://registry.npmjs.org/mongoose/-/mongoose-6.1.5.tgz",
      "dependencies": {
        // other dependencies
        "mongodb": {
          "version": "4.2.2"
        },
        // other dependencies
      }
    },
```

and mongodb-client-encryption
```
    "mongodb-client-encryption": {
      "version": "1.2.7",
      "resolved": "https://registry.npmjs.org/mongodb-client-encryption/-/mongodb-client-encryption-1.2.7.tgz",
      "dependencies": {
        // other dependencies
        "mongodb": {
          "version": "4.2.2",
          "resolved": "https://registry.npmjs.org/mongodb/-/mongodb-4.2.2.tgz",
          "dependencies": {
            "bson": {
              "version": "4.6.0"
            },
            "denque": {
              "version": "2.0.1",
              "resolved": "https://registry.npmjs.org/denque/-/denque-2.0.1.tgz"
            },
           // etc
        },
        // other dependencies
      }
    },
```
mongodb only has the dependencies listed under mongodb-client-encryption, but not under mongoose (because npm deduplicates them in the dependency tree).

If mongodb-client-encryption is skipped from adding to the bundle, but mongoose not, the dependencies for mongodb will not be included in the bundle's node_modules.

**Comment by samchungy** [comment] 2022-01-07 03:30
> Hello, everyone, the reason why this happens is because the dependencies graph generated by npm does not include all the dependencies for all the packages, some of them being duplicates. The issue happens here https://github.com/floydspace/serverless-esbuild/blob/master/src/helper.ts#L81. For example, if I run `npm ls -json -prod -all` in my project,
> 
> mongoose will have:
> 
> ```
>     "mongoose": {
>       "version": "6.1.5",
>       "resolved": "https://registry.npmjs.org/mongoose/-/mongoose-6.1.5.tgz",
>       "dependencies": {
>         // other dependencies
>         "mongodb": {
>           "version": "4.2.2"
>         },
>         // other dependencies
>       }
>     },
> ```
> 
> and mongodb-client-encryption
> 
> ```
>     "mongodb-client-encryption": {
>       "version": "1.2.7",
>       "resolved": "https://registry.npmjs.org/mongodb-client-encryption/-/mongodb-client-encryption-1.2.7.tgz",
>       "dependencies": {
>         // other dependencies
>         "mongodb": {
>           "version": "4.2.2",
>           "resolved": "https://registry.npmjs.org/mongodb/-/mongodb-4.2.2.tgz",
>           "dependencies": {
>             "bson": {
>               "version": "4.6.0"
>             },
>             "denque": {
>               "version": "2.0.1",
>               "resolved": "https://registry.npmjs.org/denque/-/denque-2.0.1.tgz"
>             },
>            // etc
>         },
>         // other dependencies
>       }
>     },
> ```
> 
> mongodb only has the dependencies listed under mongodb-client-encryption, but not under mongoose (because npm deduplicates them in the dependency tree).
> 
> If mongodb-client-encryption is skipped from adding to the bundle, but mongoose not, the dependencies for mongodb will not be included in the bundle's node_modules.

Okay so it looks like when a package is _deduped_ the package will not have a *resolved* key so we may be able to use that in order to search for the one we need?

**Comment by danionescu** [comment] 2022-01-07 09:45
I think that we actually need the “dependencies” key. A solution would be to have another object with the keys being the package names and the values the dependencies array, for all the packages in the graph returned by npm. Then we could use that in the reduce callback to build the unique array.

**Comment by danionescu** [comment] 2022-01-07 10:52
Something in the lines of

```js
const buildAllDeps = (deps) => {
  return Object.entries(deps).reduce((acc, [depName, details]) => {
    if (
      // we already have the dependencies for this package
      depName in acc && 'dependencies' in acc[depName]
    ) {
      return acc
    }

    return {
      ...acc,
      ...{ [depName]: details },
      ...(details.dependencies ? buildAllDeps(details.dependencies) : {})
    }
  }, {});
}
```
If I have enough time this weekend, I push a PR.

**Comment by danionescu** [comment] 2022-01-07 11:36
Correction (fixes some bugs and avoids reaching the maximum stack length)
Something in the lines of:
```
const buildAllDeps = (deps) => {
  if (!deps) {
    return {};
  }
  const dependenciesLeft = Object.entries(deps);
  const allDeps = {};

  while (dependenciesLeft.length > 0) {
    const [depName, details] = dependenciesLeft.shift();
    
    if (
      // we already have the dependencies for this package
      depName in allDeps && 'dependencies' in allDeps[depName]
    ) {
      continue;
    }

    if (details.dependencies) {
      Object.entries(details.dependencies).forEach((dep) => dependenciesLeft.push(dep));
    }

    allDeps[depName] = details;
  }

  return allDeps;
}
```

**Comment by samchungy** [comment] 2022-02-01 12:43
Closing this as #251 should resolve this. Please yell out if you run into any more issues!

**Comment by samchungy** [comment] 2022-02-07 08:53
#251 broke packaging logic with `yarn` packagers. Reverted the change for now. Will need to figure something out to handle the difference

**Comment by samchungy** [comment] 2022-02-07 12:13
Okay I found an issue with how we find yarn flattened tree dependencies:

sample originalObject:

```
  "bson": {
    "version": "4.6.1",
    "dependencies": {
      "buffer": {
        "version": "^5.6.0",
        "dependencies": {}
      }
    }
  },
    "buffer": {
    "version": "5.7.1",
    "dependencies": {
      "base64-js": {
        "version": "^1.3.1",
        "dependencies": {}
      },
      "ieee754": {
        "version": "^1.1.13",
        "dependencies": {}
      }
    }
  },
```

`const detailsDeps = `originalObject[depName]?.dependencies || (details as JSONObject).dependencies;`

We always look for `buffer` on the original object even if buffer might be a different version. In this case -> `5.7.1` actually fulfils ^5.6.0 but when it does not match, it will have it's own dependencies.

**Closed** 2022-02-19 04:12 UTC
Labels: released

**Comment by samchungy** [comment] 2022-02-19 08:18
Alrighty hey everyone here, I think I might have finally solved it after a fair few days of banging my head. Please give the latest package a try.

**Comment by mishabruml** [comment] 2022-03-02 09:53
Hey @samchungy I am spontaneously having issues that appear related to this https://github.com/floydspace/serverless-esbuild/issues/288

What was the fix that you deployed?
