### ISSUE TITLE
Error: spawn E2BIG

### ISSUE THREAD

**Issue by andreasgrimm** [floydspace/serverless-esbuild#166] opened 2021-07-23 09:02 UTC
If externals get over a certain number, on macOS 11.5 I'm getting this error when packaging:

```
Serverless: Compiling to node14 bundle with esbuild...
Serverless: Compiling completed.
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: < ... list of external modules>
 Error ---------------------------------------------------
 
  Error: spawn E2BIG
      at ChildProcess.spawn (internal/child_process.js:403:11)
      at spawn (child_process.js:580:9)
      at Object.spawnWithSignal [as spawn] (child_process.js:717:17)
      at /Users/.../node_modules/bestzip/lib/bestzip.js:74:29
      at /Users/.../node_modules/bestzip/node_modules/async/dist/async.js:1802:20
      at /Users/.../node_modules/bestzip/node_modules/async/dist/async.js:248:13
      at wrapper (/Users/.../node_modules/bestzip/node_modules/async/dist/async.js:268:20)
      at iterateeCallback (/Users/.../node_modules/bestzip/node_modules/async/dist/async.js:421:28)
      at /Users/.../node_modules/bestzip/node_modules/async/dist/async.js:321:20
      at /Users/.../node_modules/bestzip/node_modules/async/dist/async.js:245:17
      at /Users/.../node_modules/bestzip/node_modules/async/dist/async.js:1792:24
      at /Users/.../node_modules/bestzip/lib/bestzip.js:49:7
      at processTicksAndRejections (internal/process/task_queues.js:77:11)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.3
     Framework Version:         2.52.1 (local)
     Plugin Version:            5.4.3
     SDK Version:               4.2.5
     Components Version:        3.14.0
 
```

Same error using node version `16.5.0`.

On a Linux distro it's running fine though.

Any help would be appreciated.

**Comment by andreasgrimm** [comment] 2021-07-26 12:01
https://github.com/serverless-heaven/serverless-webpack/pull/813/files

`serverless-webpack` moved from `bestzip` to `nativeZip, nodeZip` because of the same error happing there.
Are you able to fix that in the same way?
Or would you be open to accept a PR?

**Comment by vamche** [comment] 2021-07-28 11:32
I'd like to suggest a workaround until the root cause is investigated/fixed. Since the issue seems to be because of the large number of files (externals), is deleting some of the unecessary files in `node_modules` is an option for you? You can utilize a tool like `clean-modules` or `node-prune` to clean up before zipping/packaging.

You can achieve this with `esbuild.packagerOptions.scripts`, here is an example. For more info about `clean-modules` npm package, please check https://www.npmjs.com/package/clean-modules

``` yaml
    packagerOptions:
      scripts:
        - npm install -g clean-modules
        - clean-modules -y --exclude \"test.js\" \"**/*.map.js\" --include \"**/*.d.ts\"

```

**Comment by mattjennings** [comment] 2021-07-29 22:15
A coworker and I ran into this on the same monorepo project. Packaging worked for me, but didn't for them. Same node, yarn, npm versions. I'm on macOS 11.4, they're on macOS 10.15.7.

I ended up making a patch for [patch-package](https://www.npmjs.com/package/patch-package) that changed the zip method to nodeZip. We tried nativeZip but it threw the same error.

Add this under `patches/serverless-esbuild+1.16.1.patch`

```patch
diff --git a/node_modules/serverless-esbuild/dist/utils.js b/node_modules/serverless-esbuild/dist/utils.js
index 2b0be27..580c65c 100644
--- a/node_modules/serverless-esbuild/dist/utils.js
+++ b/node_modules/serverless-esbuild/dist/utils.js
@@ -94,7 +94,7 @@ const humanSize = (size) => {
 exports.humanSize = humanSize;
 const zip = (zipPath, filesPathList, workingDir) => {
     fs.mkdirpSync(path.dirname(zipPath));
-    return bestzip_1.bestzip({
+    return bestzip_1.nodeZip({
         source: filesPathList.map((file) => file.localPath),
         destination: zipPath,
         cwd: workingDir || process.cwd()
```

**Comment by floydspace** [comment] 2021-09-04 15:44
Hey @andreasgrimm thanks for the issue, yes we're welcome to PRs. It would be good if provide a hint how to reproduce the issue. Unfortunately, I don't have such a big workload.

@mattjennings was the fix you made with `patch-package` good enough to resolve the issue?

**Comment by mattjennings** [comment] 2021-09-04 16:48
@floydspace yeah we haven't had any issues since using it

**Comment by floydspace** [comment] 2021-09-19 17:41
Hey @andreasgrimm @mattjennings I think [this fix](https://github.com/floydspace/serverless-esbuild/pull/187) would close this issue. Feel free to reopen if you still encounter it

**Closed by floydspace** 2021-09-19 17:41 UTC
