### ISSUE TITLE
Module dependencies are missing for the externals

### ISSUE THREAD

**Issue by vamche** [floydspace/serverless-esbuild#144] opened 2021-06-15 11:13 UTC
### Module dependencies are missing for the externals in the final package.

I would try to illustrate the issue with a sample repo. When I try to build the below repo, I see that the final package doesn't contain all the required dependencies. 
Repo: https://github.com/vamche/sls-esbuild-node-externals/tree/missing-module-dependecies-for-externals
Branch: `missing-module-dependecies-for-externals`

So, here the externals declared are `lodash` and `openpgp`
https://github.com/vamche/sls-esbuild-node-externals/blob/3eb11fe11c8d8088d9fe4502a3b46a195cfb6d82/serverless.yml#L17-L19
```yaml 
   external:
       - lodash
       - openpgp
```

Dependency graph for `lodash` and `openpgp`
<img width="752" alt="Screenshot 2021-06-15 at 4 33 45 PM" src="https://user-images.githubusercontent.com/9653338/122042215-7ea08f80-cdf7-11eb-8502-6f66e63f1429.png">

Though the tmp build directory (`.esbuild\.build`) contains all the modules, the final package includes only the declared modules but not all the required dependencies. In this case the `openpgp`'s dependencies are missing.
![Screenshot 2021-06-15 at 4 20 05 PM](https://user-images.githubusercontent.com/9653338/122042828-4483bd80-cdf8-11eb-99f6-9b594a7bd765.png)

<img width="268" alt="Screenshot 2021-06-15 at 4 20 56 PM" src="https://user-images.githubusercontent.com/9653338/122041321-73009900-cdf6-11eb-8faa-f489df7103f3.png">

I think the easiest way to fix this is to pass a valid depth here (may be 5?), right now the depth is missing.
https://github.com/floydspace/serverless-esbuild/blob/2fc9bb4a6a8f56b0885656bfd6fbb41656d47ac8/src/pack.ts#L103-L105

Another option I could think of is
1. Build package.json with the whitelisted deps
1. Do a packager install 
      - or copy all the node_modules and do a packager `prune`.

I would like to know your thoughts before I proceed to create a PR with one of the approaches. Please feel free to suggest if there is any better approach to resolve this.

**Comment by floydspace** [comment] 2021-06-15 11:46
Hi @vamche thanks for the new issue, I checked out your branch and ran `npx sls package` (it prepares final artifacts)
And I see that everything is packaged as you expect. 
![image](https://user-images.githubusercontent.com/5180700/122046909-ca473f00-cddf-11eb-8732-cd91efaebd67.png)
so I couldn't reproduce on my `node14`, `npm6` environment
Could you provide details about your environment? I suppose you're using `npm7`, maybe this cases the issue?

**Comment by floydspace** [comment] 2021-06-15 11:58
Indeed I checked in `node16`, `npm7` environment and it behaves as you described. I would appreciate if you make a fix, but keep in mind compatibility with older environments. Blindly passing depth 5 could break `npm6`, so you have to find the way it's working in both envs or implemented special case for `npm7` as you described. thank you

**Comment by vamche** [comment] 2021-06-15 14:24
@floydspace Thanks for testing. I have tested on my side, I confirm that it's working with `npm6`. The issue is with `npm7` only because of the change in output of `npm ls -prod -json`.

As you suggested, I will try to find a way which is backward compatible.

**Closed** 2021-12-15 22:11 UTC
