### ISSUE TITLE
Sourcemaps not being parsed properly?

### ISSUE THREAD

**Issue by kennandavison** [floydspace/serverless-esbuild#99] opened 2021-03-11 07:37 UTC
Hey! Not sure if I'm doing something wrong here, but I see the sourcemap next to my files and it's not being parsed by my log viewer... Anyone else using source maps?

https://github.com/floydspace/serverless-esbuild/issues/91

**Comment by floydspace** [comment] 2021-03-11 12:37
hey @kennandavison could you try using inline sourcemaps to reduce the number of the possible reasons of the issue
```
custom:
  esbuild:
    sourcemap: inline
```

**Comment by kennandavison** [comment] 2021-03-11 12:53
Tried that and still having troubles getting sourcemap associated. 

More context: using seed.run (which has a Sentry-like stack trace viewer). Was using serverless-bundle which worked, but not working here. Trying to also see if it's on their end as well!

**Comment by floydspace** [comment] 2021-03-14 19:00
Hey @kennandavison, I'm trying to test the issue. Have prepared the [stack for seed.run](https://github.com/floydspace/serverless-esbuild-seed.run-example), it's perfectly deployed, but not sure how to reproduce your issue, could you please guide me where is that `Sentry-like stack trace viewer`. thank you

**Comment by kennandavison** [comment] 2021-03-14 19:22
https://seed.run/docs/issues-and-alerts.html#enabling-issues should get it up and running

**Comment by floydspace** [comment] 2021-03-14 19:38
@kennandavison I bet you're expecting stack trace like this:
![image](https://user-images.githubusercontent.com/5180700/111081746-1cd53e80-8505-11eb-895c-d489fa879eb5.png)
with exact pointer where is the issue?

**Comment by kennandavison** [comment] 2021-03-14 19:42
Yep, the line number/pointer is off when using esbuild, but correct when using serverless bundle. Are you seeing the same thing?

**Comment by floydspace** [comment] 2021-03-14 19:47
@kennandavison yes I could reproduce it. so with `serverless-esbuild` plugin I cannot see the pointer to the source code line.
But I cannot help here much, because it's [esbuild](https://esbuild.github.io/api/#sourcemap) feature itself. Esbuild just creates source maps a little bit differently than webpack. I would raise the issue in their repository. My assumption is you probably have to push source code to lambda along with bundled one to have it worked.

**Comment by floydspace** [comment] 2021-03-14 20:02
@kennandavison no the assumption does not work either, so it's definitely `esbuild` issue

**Comment by kennandavison** [comment] 2021-03-14 20:05
Got it - thanks for checking this out!

**Comment by floydspace** [comment] 2021-03-14 20:08
@kennandavison let me know if you gonna raise the issue in `esbuild` repo.
Closing this issue.

**Closed by floydspace** 2021-03-14 20:08 UTC
Labels: wontfix

**Comment by kennandavison** [comment] 2021-03-26 02:07
Hey - turns out you just need to add an env var! Serverless-bundle automatically does this while esbuild doesn't. https://serverless.pub/aws-lambda-node-sourcemaps/#using-the-source-map-support-module

Hope this helps someone else using sourcemaps :)

**Comment by pierreh** [comment] 2023-08-08 19:03
also make sure to use `sourcemaps: true` instead of `sourcemaps: external` this will set `sourceMappingURL` correctly.
