### ISSUE TITLE
Any way to use `knex`?

### ISSUE THREAD

**Issue by arpadgabor** [floydspace/serverless-esbuild#114] opened 2021-04-14 18:30 UTC
Currently trying to package `knex` with `pg`. This was also a problem `serverless-webpack` faced but by force including the required packages it worked in the end. [This is the only issue](https://github.com/evanw/esbuild/issues/473) that I could find related to knex and esbuild but doesn't seem to solve my problem.

This is the error I get when running `sls package`:

```sh
# ...

Serverless: Packing external modules: knex@^0.95.4, mysql, mysql2, pg@^8.6.0, pg-native, sqlite3, tedious

Error ---------------------------------------------------
 
Error: npm install failed with code 1
   at ChildProcess.<anonymous> (/home/arpad/workspace/sls-webpack-v-esbuild/esbuild/node_modules/serverless-esbuild/dist/utils.js:48:24)
   at ChildProcess.emit (events.js:314:20)
   at ChildProcess.EventEmitter.emit (domain.js:483:12)
   at maybeClose (internal/child_process.js:1022:16)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

# ...
```
To note that it also tries to include `mysql`, `mysql2`, `pg-native`, `sqlite3` and `tedious` and I'm not sure how I can ignore them.

And this is my config:

```ts
// ...

custom: {
  esbuild: {
    bundle: true,
    minify: false,
    external: ['knex', 'pg'],
  },
},

package: {
  individually: true,
},

// ...
```

**Comment by olup** [comment] 2021-04-14 18:35
You might have an error file in `.serverless/build` with more details about the error ?

**Comment by arpadgabor** [comment] 2021-04-14 18:42
It doesn't generate any log file, here's a screenshot:

![image](https://user-images.githubusercontent.com/9270494/114762139-10453f80-9d6a-11eb-910b-d41757d193b9.png)

And here's the whole output with `SLS_DEBUG=*`

```
Serverless: Load command interactiveCli
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command config:tabcompletion
Serverless: Load command config:tabcompletion:install
Serverless: Load command config:tabcompletion:uninstall
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command upgrade
Serverless: Load command uninstall
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command generate-event
Serverless: Load command test
Serverless: Load command dashboard
Serverless: Load command output
Serverless: Load command output:get
Serverless: Load command output:list
Serverless: Load command param
Serverless: Load command param:get
Serverless: Load command param:list
Serverless: Load command studio
Serverless: Skipping variables resolution with old resolver (new resolver reported no more variables to resolve)
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Compiling with esbuild...
Serverless: Compiling completed.
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: knex@^0.95.4, mysql, mysql2, pg@^8.6.0, pg-native, sqlite3, tedious
 
 Error ---------------------------------------------------
 
  Error: npm install failed with code 1
      at ChildProcess.<anonymous> (/home/arpad/workspace/sls-webpack-v-esbuild/esbuild/node_modules/serverless-esbuild/dist/utils.js:48:24)
      at ChildProcess.emit (events.js:314:20)
      at ChildProcess.EventEmitter.emit (domain.js:483:12)
      at maybeClose (internal/child_process.js:1022:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.20.1
     Framework Version:         2.35.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.8.2
```

I can set up a test repo if it helps.

**Comment by olup** [comment] 2021-04-14 19:30
Sorry I meant in `.esbuild/.build` but it looks like you don't have anything. Maybe a yarn thing ? Anyway, I'll try to reproduce on my end and will be glad for a test respo if I can't.

**Comment by arpadgabor** [comment] 2021-04-14 19:41
Also tested with yarn (1.22.10) and still no file. Similar output:

```
Serverless: Packing external modules: knex@^0.95.4, mysql, mysql2, pg@^8.6.0, pg-native, sqlite3, tedious
 
 Error ---------------------------------------------------
 
  Error: yarn install --frozen-lockfile --non-interactive failed with code 1
      at ChildProcess.<anonymous> (/home/arpad/workspace/sls-webpack-v-esbuild/esbuild/node_modules/serverless-esbuild/dist/utils.js:48:24)
      at ChildProcess.emit (events.js:314:20)
      at ChildProcess.EventEmitter.emit (domain.js:483:12)
      at maybeClose (internal/child_process.js:1022:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

Here's [my testing repo](https://github.com/arpadgabor/serverless-esbuild-test).

**Comment by olup** [comment] 2021-04-14 19:47
Great, thx a lot.

@floydspace btw, I think esbuild's exclude option should also be considered when pulling externals peer deps no ? It is for externals first layer, but not when getting peer deps, but the need to exclude some of them has surfaced a few times recently. What do you think ? In this case it would totally help.

**Comment by olup** [comment] 2021-04-14 20:11
@arpadgabor weird - I am packaging your test repo without error when using npm. I am getting an error with yarn but i'd say it's related of the frozen lockfile and some libs without version number, but i'll dig...

**Comment by arpadgabor** [comment] 2021-04-14 20:21
Cloned my repo in another folder and tried again. I'm still getting the error even after removing both node_modules and package-lock, and trying with npm `7.9.0` and node `14.16.1`. Weird..

**Comment by olup** [comment] 2021-04-14 20:23
@arpadgabor note that I made a PR yesterday to NOT auto bundle the OPTIONAL dependencies of the external (branch fix.peer-deps). I just tryed your test repo with it, and it seems to work even better. Could you try and deploy your project with it ?

just `yarn install https://github.com/floydspace/serverless-esbuild.git#fix/peer-deps`

**Comment by arpadgabor** [comment] 2021-04-14 20:51
No luck.. this is very weird, the package is in present `node_modules`.
```
Serverless Error ----------------------------------------
 
  Serverless plugin "serverless-esbuild" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

...
```
```json
// package.json
"devDependencies": {
    "serverless-esbuild": "https://github.com/floydspace/serverless-esbuild.git#fix/peer-deps",
}
```

**Comment by olup** [comment] 2021-04-14 20:53
oh sorry of course, it needs deps install and building in the node modules - you cannot try it just like that

**Comment by arpadgabor** [comment] 2021-04-14 20:56
Yep, now it's working perfectly!

```
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: Compiling with esbuild...
Serverless: Compiling completed.
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: knex@^0.95.4, pg@^8.6.0
Serverless: Zip function: esbuild-testing-zone-dev-create - 27.95 KB [74 ms]
Serverless: Zip function: esbuild-testing-zone-dev-findById - 27.98 KB [59 ms]
Serverless: Zip function: esbuild-testing-zone-dev-find - 1.14 MB [612 ms]
Serverless: Packaging service...
```

**Comment by arpadgabor** [comment] 2021-04-14 21:10
@olup After a closer inspection (I only packaged it earlier, deployed now), it seems like it missed (at least) a package (`ms`) used by knex. Here's the error from CloudWatch.

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'ms'\nRequire stack:\n- /var/task/node_modules/debug/src/common.js\n- /var/task/node_modules/debug/src/node.js\n- /var/task/node_modules/debug/src/index.js\n- /var/task/node_modules/knex/lib/execution/transaction.js\n- /var/task/node_modules/knex/lib/client.js\n- /var/task/node_modules/knex/lib/knex-builder/Knex.js\n- /var/task/node_modules/knex/lib/index.js\n- /var/task/node_modules/knex/knex.js\n- /var/task/src/functions/cars/find/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'ms'",
        "Require stack:",
        "- /var/task/node_modules/debug/src/common.js",
        "- /var/task/node_modules/debug/src/node.js",
        "- /var/task/node_modules/debug/src/index.js",
        "- /var/task/node_modules/knex/lib/execution/transaction.js",
        "- /var/task/node_modules/knex/lib/client.js",
        "- /var/task/node_modules/knex/lib/knex-builder/Knex.js",
        "- /var/task/node_modules/knex/lib/index.js",
        "- /var/task/node_modules/knex/knex.js",
        "- /var/task/src/functions/cars/find/handler.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1063:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)",
        "    at Module.load (internal/modules/cjs/loader.js:928:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:769:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by olup** [comment] 2021-04-14 21:24
This is weird. ms is a dependency of a dependency of an external, it should be added to the node modules. Thanks for reporting.

**Comment by arpadgabor** [comment] 2021-04-14 21:26
Replying here in case you haven't noticed the edit, `pg` is actually not included at all, only `pg-connection-string`.

**Comment by olup** [comment] 2021-04-14 21:29
It's a bug in the individual packaging logic. This doesn't happen when doing global packaging. Will fix asap.

**Comment by arpadgabor** [comment] 2021-04-14 21:31
Offtopic but, thanks for all the help and for all of the fast replies! Going offline as it's midnight, will report back tomorrow if there are any updates.

**Comment by olup** [comment] 2021-04-14 21:34
Interesting case here... I don't know why ms is not here, but pg is missing because it is not actually required anywhere in the js bundle, as it is "magically" resolved by knex. In individual packaging, we bundle only libs that are actually required in the code and the one they need - but that doesn't take into account optional peer dependencies...

**Comment by arpadgabor** [comment] 2021-04-15 07:52
Okay so after importing `pg` explicitly, it's now working correctly.

**Closed** 2021-04-15 21:35 UTC
