### ISSUE TITLE
Unable to bundle individual packages with pnpm

### ISSUE THREAD

**Issue by blazejkustra** [floydspace/serverless-esbuild#365] opened 2022-08-30 10:47 UTC
**Describe the bug**
Hi, I have problems to package lambda with external modules using pnpm. I don't have node_modules in the .zip file when using pnpm, with npm it works fine. 

**To Reproduce**
Here is sample repo: [link](https://github.com/blazejkustra/esbuild-test)
1. install pnpm and npx
2. install dependencies with `pnpm i`
3. `npx serverless package` <- this throws errors

Scenarios:
1. With `custom.esbuild.packager = "npm"` it builds and `node_modules` are included in `.serverless/test.zip` 
2. With `custom.esbuild.packager = "pnpm"` it builds with an error:
```
Error:
Error: pnpm install --frozen-lockfile failed with code 1
    at ChildProcess.<anonymous> (/Users/blazejkustra/Documents/swmansion/esbuild-test/node_modules/.pnpm/serverless-esbuild@1.32.8_esbuild@0.15.6/node_modules/serverless-esbuild/dist/utils.js:53:24)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```
3. With `custom.esbuild.packager = "pnpm"` and no `custom.esbuild.external` it works fine but I don't have modules in node modules which breaks `@sparticuz/chrome-aws-lambda` package (it uses puppeteer under the hood in a weird way - that's why I want to make it as external module).

**Expected behavior**
I expect that it should be possible to package lambdas with `npx serverless package` with some external modules in `node_modules` using `pnpm` and `custom.esbuild.external` option.

**Versions (please complete the following information):**
OS: Mac os M2
serverless: 3.22.0
esbuild: 0.15.5
serverless-esbuild: 1.32.8

**Additional context**
I need to make `@sparticuz/chrome-aws-lambda` as external because of this code in the library: 
![image](https://user-images.githubusercontent.com/46095609/187417085-bce3273b-b5ec-4a16-8c6f-ddaf4500f436.png)

This causes problems at runtime (because `pnpm` uses symlinks and no module can be found):
![image](https://user-images.githubusercontent.com/46095609/187417588-8c4ac003-1751-433e-b254-f2498f078e89.png)

**Comment by samchungy** [comment] 2022-08-30 12:55
duplicate of https://github.com/floydspace/serverless-esbuild/issues/269

**Closed by samchungy** 2022-08-30 12:55 UTC
Labels: bug
